### ISSUE TITLE
`docker-compose.yml` 간소화

### ISSUE THREAD

**Issue by dongwook-chan** [23-OSSCA-python-mysql-replication/python-mysql-replication#23]
앞으로 버전/벤더별로 많은 서비스들이 추가될 수 있을 것 같은데요,
제가 예전에 작성했던 테스트 돌리려면 적어도 MySQL 8.0.16는 추가되어야 할 것 같네요
YAML anchor 기능을 활용해서 공통 되는 설정값들을 간소하게/깔끔하게 표현할 수 있을 것 같아서 원본 reop에 PR 넣어보려고 합니다.
충은님(@cucuridas)이 깔끔하게 작성해주신 [docker-compose.yml](https://github.com/23-OSSCA-python-mysql-replication/python-mysql-replication/blob/1fb152269c0c4da19e865421c42a40b7e55605e8/docker-compose.yml#L19-L30)에 영감을 받아 숟가락 얹어 봅니다.

수정 전
```yaml
version: '3.2'
services:
  percona-5.7:
    image: percona:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - 3306:3306
    command: mysqld --log-bin=mysql-bin.log --server-id 1 --binlog-format=row --gtid_mode=on --enforce-gtid-consistency=on --log_slave_updates

  percona-5.7-ctl:
    image: percona:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - 3307:3307
    command: mysqld --log-bin=mysql-bin.log --server-id 1 --binlog-format=row --gtid_mode=on --enforce-gtid-consistency=on --log_slave_updates -P 3307

  percona-8.0.16:
    image: percona:8.0.16
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - 3307:3307
    command: mysqld --log-bin=mysql-bin.log --server-id 1 --binlog-format=row --gtid_mode=on --enforce-gtid-consistency=on --log_slave_updates -P 3307

  mariadb-10.6:
    image: mariadb:10.6
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    ports:
      - "3308:3306"
    command: |
      --server-id=1
      --default-authentication-plugin=mysql_native_password
      --log-bin=master-bin
      --binlog-format=row
      --log-slave-updates=on
```

수정 후
```yaml
version: '3.2'

x-mysql: &mysql
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: true
  command: >
    mysqld
    --log-bin=mysql-bin.log
    --server-id 1
    --binlog-format=row
    --gtid_mode=on
    --enforce-gtid-consistency=on
    --log_slave_updates

x-mariadb: &mariadb
  environment:
    MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
  command: |
    --server-id=1
    --default-authentication-plugin=mysql_native_password
    --log-bin=master-bin
    --binlog-format=row
    --log-slave-updates=on
  
services:
  percona-5.7:
    <<: *mysql
    image: percona:5.7
    ports:
      - 3306:3306

  percona-5.7-ctl:
    <<: *mysql
    image: percona:5.7
    ports:
      - 3307:3306
      
  percona-8.0.16:
    <<: *mysql
    image: percona:8.0.16
    ports:
      - 3309:3306

  mariadb-10.6:
    <<: *mariadb
    image: mariadb:10.6
    ports:
      - 3308:3306
```
