### ISSUE TITLE
로깅 추가

### ISSUE THREAD

**Issue by dongwook-chan** [23-OSSCA-python-mysql-replication/python-mysql-replication#50]
본 라이브러리의 사용자가 활용할 수 있는 어떠한 로그도 제공되고 있지 않습니다.
다음의 예시처럼 로깅 수준 별로 기록될 로그 항목들을 정하고
사용자가 보기 쉬운 포맷으로 제공하면 좋을 것 같습니다.

### ERROR
CRC 체크를 통과하지 못한 경우
### WARN
과제#2 이슈 케이스에 해당하는 경우
### INFO
이벤트 스트림의 시작과 끝
### DEBUG
주요 이벤트에 대한 간단한 덤프

**Comment by why-arong** [comment]
# ERROR

### event.py: BinLogEvent
<img width="578" alt="Screenshot 2023-08-13 at 9 09 11 PM" src="https://github.com/23-OSSCA-python-mysql-replication/python-mysql-replication/assets/68311908/d825d6ab-2bd8-4f6e-831e-4de164d31e42">

### binlogstream.py : BinLogStreamReader
<img width="872" alt="Screenshot 2023-08-13 at 9 09 27 PM" src="https://github.com/23-OSSCA-python-mysql-replication/python-mysql-replication/assets/68311908/629ba518-c7fd-4810-bf03-644d2ea47b50">

## terminal output
<img width="1236" alt="Screenshot 2023-08-13 at 9 09 48 PM" src="https://github.com/23-OSSCA-python-mysql-replication/python-mysql-replication/assets/68311908/7b8e83a5-d34e-44c0-8b70-d3a1da5a80dc">

현재 간단한게 위와 같이 작성했습니다. 
지금은 BinLogStreamReader에 설정 값을 작성했는데
config file을 만들어 여기에 작성하는 것으로 해야 할까요? 또 콘솔말고도 저장될 .log 를 만드는 것은 어떤가요?

```yaml
# config.yaml
version: 1
formatters:
  detailed:
    format: '%(levelname)s (%(asctime)s): %(message)s (Line: %(lineno)d [%(filename)s])'
    datefmt: '%d/%m/%Y %I:%M:%S %p'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: detailed
  file:
    class: logging.FileHandler
    filename: app.log  # 로그 파일의 경로 및 이름
    level: DEBUG
    formatter: detailed
root:
  level: DEBUG
  handlers: [console, file]  # 여기서 file 핸들러를 추가

```

```python3
import logging
import logging.config
import yaml

# 로깅 설정 파일 로드
with open('logging_config.yaml', 'r') as config_file:
    config = yaml.safe_load(config_file)

# 로깅 설정 적용
logging.config.dictConfig(config)
```
